#!/bin/sh

# initialize cgroups
[ -f /sys/fs/cgroup/cgroup.subtree_control ] || busybox mount -o nosuid,nodev,noexec -t cgroup2 cgroup2 /sys/fs/cgroup
[ -d /sys/fs/cgroup ] && echo "+cpu +pids +memory" > /sys/fs/cgroup/cgroup.subtree_control

# allocate a 2MB hugepage for memory mapped devices
busybox grep -Fq hugetlbfs /proc/filesystems && echo 1 > /proc/sys/vm/nr_hugepages

# security
busybox mount -o noatime,nosuid,remount /
busybox mount -o nosuid,remount /dev
# busybox mount -o ro,remount /
