require '.sha3'

global function keccak256(data: span(byte)): [32]byte
  local hash: [32]byte
  assert(sha3_HashBuffer(256, SHA3_FLAGS_KECCAK, data.data, data.size, &hash, #hash) == SHA3_RETURN_OK, 'keccak failed')
  return hash
end

global function hexhash(hash: [32]byte): string
  local sb: stringbuilder <close>
  for _, b: byte in ipairs(hash) do
    sb:writef('%02x', b)
  end
  return sb:promote()
end
