local allowed_syscalls = {
  -- basic IO
  '_llseek',
  'close',
  'close_range',
  'lseek',
  'pread64',
  'preadv',
  'preadv2',
  'pwrite64',
  'pwritev',
  'pwritev2',
  'read',
  'readv',
  'write',
  'writev',

  -- signal handling
  'rt_sigaction',
  'rt_sigpending',
  'rt_sigprocmask',
  'rt_sigqueueinfo',
  'rt_sigreturn',
  'rt_sigsuspend',
  'rt_sigtimedwait',
  'rt_sigtimedwait_time64',
  'rt_tgsigqueueinfo',
  'sigaction',
  'sigaltstack',
  'signal',
  'signalfd',
  'signalfd4',
  'sigpending',
  'sigprocmask',
  'sigreturn',
  'sigsuspend',

  -- filesystem
  'access',
  'faccessat',
  'faccessat2',
  'chdir',
  'fchdir',
  'chmod',
  'fchmod',
  'fchmodat',
  'link',
  'linkat',
  'readlink',
  'readlinkat',
  'symlink',
  'symlinkat',
  'unlink',
  'unlinkat',
  'rmdir',
  'rename',
  'renameat',
  'renameat2',
  'fcntl',
  'fcntl64',
  'fstat',
  'fstat64',
  'fstatat64',
  'fstatfs',
  'fstatfs64',
  'lstat',
  'lstat64',
  'newfstatat',
  'oldfstat',
  'oldlstat',
  'oldstat',
  'stat',
  'stat64',
  'statfs',
  'statfs64',
  'statx',
  'ftruncate',
  'ftruncate64',
  'truncate',
  'truncate64',
  'futimesat',
  'utime',
  'utimensat',
  'utimensat_time64',
  'utimes',
  'fallocate',
  'getcwd',
  'getdents',
  'getdents64',
  'mkdir',
  'mkdirat',
  'mknod',
  'mknodat',
  'umask',

  -- fd creation
  'creat',
  'open',
  'openat',
  'openat2',
  'dup',
  'dup2',
  'dup3',
  'open_by_handle_at',
  'name_to_handle_at',

  -- piping
  'copy_file_range',
  'pipe',
  'pipe2',
  'sendfile',
  'sendfile64',
  'splice',
  'tee',
  'vmsplice',

  -- sync
  'fdatasync',
  'fsync',
  'msync',
  'sync',
  'sync_file_range',
  'sync_file_range2',
  'syncfs',

  -- process spawning
  'brk',
  'clone',
  'clone3',
  'execve',
  'execveat',
  'fork',
  'vfork',

  -- process termination
  'kill',
  'exit',
  'exit_group',

  -- current state information
  'getegid',
  'getegid32',
  'geteuid',
  'geteuid32',
  'getgid',
  'getgid32',
  'getgroups',
  'getgroups32',
  'getpgid',
  'getpgrp',
  'getpid',
  'getppid',
  'getrandom',
  'getresgid',
  'getresgid32',
  'getresuid',
  'getresuid32',
  'getsid',
  'gettid',
  'getuid',
  'getuid32',

  -- threads
  'get_thread_area',
  'set_thread_area',
  'set_tid_address',
  'tgkill',
  'tkill',

  -- allow getting time
  'clock_getres',
  'clock_getres_time64',
  'clock_gettime',
  'clock_gettime64',
  'gettimeofday',
  'time',
  'times',

  -- process suspension
  'clock_nanosleep',
  'clock_nanosleep_time64',
  'nanosleep',
  'pause',
  'wait4',
  'waitid',
  'waitpid',
  'sched_yield',

  -- virtual memory mapping
  'membarrier',
  'mmap',
  'mmap2',
  'mprotect',
  'munmap',

  -- RISC-V only
  'riscv_flush_icache',

  -- event loop
  '_newselect',
  'eventfd',
  'eventfd2',
  'ioctl',
  'poll',
  'ppoll',
  'ppoll_time64',
  'pselect6',
  'pselect6_time64',
  'select',

  -- other
  'arch_prctl',
  'cacheflush',
  'rseq',
}

local disallowed_syscalls = {
  -- epoll
  'epoll_create',
  'epoll_create1',
  'epoll_ctl',
  'epoll_ctl_old',
  'epoll_pwait',
  'epoll_pwait2',
  'epoll_wait',
  'epoll_wait_old',

  -- filesystem xattr
  'fgetxattr',
  'flistxattr',
  'fremovexattr',
  'fsetxattr',
  'getxattr',
  'lgetxattr',
  'listxattr',
  'llistxattr',
  'lremovexattr',
  'lsetxattr',
  'removexattr',
  'setxattr',

  --- futex
  'get_robust_list',
  'set_robust_list',
  'futex',
  'futex_time64',
  'futex_waitv',

  -- system information
  'capget',
  'getcpu',
  'getpriority',
  'getrlimit',
  'getrusage',
  'oldolduname',
  'olduname',
  'sysinfo',
  'ugetrlimit',
  'uname',

  -- inter process communication
  'ipc',
  'memfd_create',
  'memfd_secret',
  'mq_getsetattr',
  'mq_notify',
  'mq_open',
  'mq_timedreceive',
  'mq_timedreceive_time64',
  'mq_timedsend',
  'mq_timedsend_time64',
  'mq_unlink',
  'msgctl',
  'msgget',
  'msgrcv',
  'msgsnd',
  'pidfd_getfd',
  'pidfd_open',
  'pidfd_send_signal',
  'process_madvise',
  'process_mrelease',
  'process_vm_readv',
  'process_vm_writev',
  'semctl',
  'semget',
  'semop',
  'semtimedop',
  'semtimedop_time64',
  'shmat',
  'shmctl',
  'shmdt',
  'shmget',

  -- scheduler information
  'sched_get_priority_max',
  'sched_get_priority_min',
  'sched_getaffinity',
  'sched_getattr',
  'sched_getparam',
  'sched_getscheduler',
  'sched_rr_get_interval',
  'sched_rr_get_interval_time64',

  -- advanced filesystem
  'fadvise64',
  'fadvise64_64',
  'flock',
  'readahead',
  'readdir',

  -- scheduler sets
  'sched_setaffinity',
  'sched_setattr',
  'sched_setparam',
  'sched_setscheduler',

  -- set resources
  'nice',
  'ioprio_get',
  'ioprio_set',
  'setpriority',
  'setrlimit',
  'move_pages',
  'mbind',
  'get_mempolicy',
  'set_mempolicy',
  'set_mempolicy_home_node',
  'migrate_pages',
  'prctl',
  'prlimit64',

  -- raw io
  'ioperm',
  'iopl',
  'pciconfig_iobase',
  'pciconfig_read',
  'pciconfig_write',

  -- memory lock
  'mlock',
  'mlock2',
  'mlockall',
  'munlock',
  'munlockall',

  -- advanced memory control
  'madvise',
  'mremap',
  'mincore',

  -- landlock
  'landlock_add_rule',
  'landlock_create_ruleset',
  'landlock_restrict_self',

  -- aio
  'io_cancel',
  'io_destroy',
  'io_getevents',
  'io_pgetevents',
  'io_pgetevents_time64',
  'io_setup',
  'io_submit',
  'io_uring_enter',
  'io_uring_register',
  'io_uring_setup',

  -- networking
  'accept',
  'accept4',
  'bind',
  'connect',
  'getpeername',
  'getsockname',
  'getsockopt',
  'listen',
  'recv',
  'recvfrom',
  'recvmmsg',
  'recvmmsg_time64',
  'recvmsg',
  'send',
  'sendmmsg',
  'sendmsg',
  'sendto',
  'setsockopt',
  'shutdown',
  'socket',
  'socketcall',
  'socketpair',

  -- filesystem chown
  'chown',
  'chown32',
  'fchown',
  'fchown32',
  'fchownat',
  'lchown',
  'lchown32',

  -- memory protection keys
  'pkey_alloc',
  'pkey_free',
  'pkey_mprotect',

  -- swap
  'swapoff',
  'swapon',

  -- set gid/uid
  'setfsgid',
  'setfsgid32',
  'setfsuid',
  'setfsuid32',
  'setgid',
  'setgid32',
  'setgroups',
  'setgroups32',
  'setpgid',
  'setregid',
  'setregid32',
  'setresgid',
  'setresgid32',
  'setresuid',
  'setresuid32',
  'setreuid',
  'setreuid32',
  'setsid',
  'setuid',
  'setuid32',

  -- inotify
  'fanotify_init',
  'fanotify_mark',
  'inotify_add_watch',
  'inotify_init',
  'inotify_init1',
  'inotify_rm_watch',

  -- timer
  'alarm',
  'getitimer',
  'setitimer',
  'timer_create',
  'timer_delete',
  'timer_getoverrun',
  'timer_gettime',
  'timer_gettime64',
  'timer_settime',
  'timer_settime64',
  'timerfd',
  'timerfd_create',
  'timerfd_gettime',
  'timerfd_gettime64',
  'timerfd_settime',
  'timerfd_settime64',

  -- set clock
  'adjtimex',
  'clock_adjtime',
  'clock_adjtime64',
  'clock_settime',
  'clock_settime64',
  'settimeofday',

  -- manipulating kernel modules
  'create_module',
  'delete_module',
  'finit_module',
  'init_module',
  'query_module',

  -- ARM only
  'arm_fadvise64_64',
  'arm_sync_file_range',
  'breakpoint',
  'get_tls',
  'set_tls',
  'usr26',
  'usr32',

  -- s390 only
  's390_guarded_storage',
  's390_pci_mmio_read',
  's390_pci_mmio_write',
  's390_runtime_instr',
  's390_sthyi',

  -- powerpc only
  'rtas',
  'spu_create',
  'spu_run',
  'subpage_prot',
  'swapcontext',
  'switch_endian',
  'sys_debug_setcontext',

  -- mips only
  'cachectl',
  'sysmips',

  -- x86 only
  'vm86',
  'vm86old',

  -- reading current quota use
  'quotactl',
  'quotactl_fd',

  -- access to the kernel keyring
  'add_key',
  'keyctl',
  'request_key',

  -- sub-namespaces
  'unshare',
  'setns',
  'mount',
  'umount',
  'umount2',
  'pivot_root',
  'chroot',

  -- new mount manipulation APIs
  'fsconfig',
  'fsmount',
  'fsopen',
  'fspick',
  'mount_setattr',
  'move_mount',
  'open_tree',

  -- privileged
  'acct',
  'bpf',
  'capset',
  'kcmp',
  'kexec_file_load',
  'kexec_load',
  'lookup_dcookie',
  'modify_ldt',
  'perf_event_open',
  'personality',
  'ptrace',
  'reboot',
  'restart_syscall',
  'seccomp',
  'setdomainname',
  'sethostname',
  'syscall',
  'syslog',
  'userfaultfd',
  'vhangup',

  -- obsolete syscalls
  '_sysctl',
  'afs_syscall',
  'bdflush',
  'break',
  'ftime',
  'get_kernel_syms',
  'getpmsg',
  'gtty',
  'idle',
  'lock',
  'mpx',
  'multiplexer',
  'nfsservctl',
  'prof',
  'profil',
  'putpmsg',
  'remap_file_pages',
  'security',
  'sgetmask',
  'ssetmask',
  'stime',
  'stty',
  'sysfs',
  'tuxcall',
  'ulimit',
  'uselib',
  'ustat',
  'vserver',
}

local f = assert(io.open('seccomp-rules.h', 'w'))
for _,name in ipairs(allowed_syscalls) do
  local line = string.format("ALLOW_RULE(%s)\n", name)
  f:write(line)
end
f:close()

print('allowed', #allowed_syscalls)
print('disallowed', #disallowed_syscalls)
assert(#allowed_syscalls + #disallowed_syscalls == 481)
